// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRmogrwXEtlpdmTFevt1nNJZ78RfjNjs',
    appId: '1:221712438995:web:3dbebfa7bfc39a31912626',
    messagingSenderId: '221712438995',
    projectId: 'argumentia-68101',
    authDomain: 'argumentia-68101.firebaseapp.com',
    storageBucket: 'argumentia-68101.firebasestorage.app',
    measurementId: 'G-T0XZD051GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvuU3lvI1eEwvtsGtI58A3nFCnXsiNVbk',
    appId: '1:221712438995:android:820a7438c3739022912626',
    messagingSenderId: '221712438995',
    projectId: 'argumentia-68101',
    storageBucket: 'argumentia-68101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6U_Gz-23xIEwVlkX1GAabO9-QTPkJ6g',
    appId: '1:221712438995:ios:6e92dd3f8a26ffa6912626',
    messagingSenderId: '221712438995',
    projectId: 'argumentia-68101',
    storageBucket: 'argumentia-68101.firebasestorage.app',
    iosBundleId: 'com.example.argumenta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6U_Gz-23xIEwVlkX1GAabO9-QTPkJ6g',
    appId: '1:221712438995:ios:6e92dd3f8a26ffa6912626',
    messagingSenderId: '221712438995',
    projectId: 'argumentia-68101',
    storageBucket: 'argumentia-68101.firebasestorage.app',
    iosBundleId: 'com.example.argumenta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRmogrwXEtlpdmTFevt1nNJZ78RfjNjs',
    appId: '1:221712438995:web:051a100a4c56ca98912626',
    messagingSenderId: '221712438995',
    projectId: 'argumentia-68101',
    authDomain: 'argumentia-68101.firebaseapp.com',
    storageBucket: 'argumentia-68101.firebasestorage.app',
    measurementId: 'G-SY7MFD44B5',
  );
}
